# Generated by Django 2.2.1 on 2019-10-31 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userinfo', models.CharField(blank=True, max_length=150, verbose_name='上传用户')),
                ('codename', models.CharField(blank=True, max_length=50, verbose_name='程序名')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='程序描述')),
                ('fav_nums', models.IntegerField(blank=True, default=0, verbose_name='点赞人数')),
                ('download_nums', models.IntegerField(blank=True, default=0, verbose_name='下载数')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='添加时间')),
                ('syntax_check', models.BooleanField(blank=True, default=False, verbose_name='语法审核')),
                ('manual_check', models.BooleanField(blank=True, default=False, verbose_name='人工审核')),
                ('codefile', models.FileField(blank=True, upload_to='codefile/')),
            ],
            options={
                'verbose_name': '代码信息',
                'verbose_name_plural': '代码信息',
            },
        ),
    ]
