# Generated by Django 2.2.1 on 2019-11-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': '上传代码列表', 'verbose_name_plural': '上传代码列表'},
        ),
    ]
