# Generated by Django 2.2.1 on 2019-11-06 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20191104_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Like_user', models.CharField(blank=True, max_length=150, verbose_name='点赞用户')),
                ('Like_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='点赞时间')),
                ('Like_codefile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Code', to='coding.Code')),
            ],
            options={
                'verbose_name': '点赞列表',
                'verbose_name_plural': '点赞列表',
            },
        ),
    ]
