# Generated by Django 2.2.1 on 2019-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_likerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='star_check',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否上星'),
        ),
    ]
