# Generated by Django 2.2.1 on 2019-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191030_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='生日'),
        ),
    ]
