# Generated by Django 2.2.1 on 2019-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='files/')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'File',
                'db_table': 'File',
            },
        ),
    ]
