# Generated by Django 2.2.1 on 2019-11-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20191027_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
    ]
